-- 계정생성
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER todolist IDENTIFIED BY todolist1234;
GRANT CONNECT, RESOURCE TO todolist;
ALTER USER todolist DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;