CREATE TABLE "MEMBER" (
   "MEMBER_NO"   NUMBER   PRIMARY KEY,
   "MEMBER_EMAIL"   VARCHAR2(50) NOT NULL,
   "MEMBER_PW"   VARCHAR2(30) NOT NULL,
   "MEMBER_NICK"   VARCHAR2(30) NOT NULL,
   "MEMBER_TEL"   CHAR(11) NOT NULL,
   "MEMBER_ADDR"   VARCHAR2(500),
   "PROFILE_IMG"   VARCHAR2(200),
   "ENROLL_DT"   DATE DEFAULT SYSDATE ,
   "SECESSION_FL"   CHAR(1)   DEFAULT 'N'
);


COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일(아이디)';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICK" IS '회원 닉네임(중복x)';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호(- 미포함)';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDR" IS '회원 주소';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필 이미지';
COMMENT ON COLUMN "MEMBER"."ENROLL_DT" IS '회원 가입일';
COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴여부(Y:탈퇴, N:미탈퇴)';


-- 회원 번호 시퀀스
CREATE SEQUENCE SEQ_MEMBER_NO;

INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01@kh.or.kr', 'pass01!', 
    '유저일', '01012341234', '04540,,서울특별시 강남구 테헤란로 14길 6 5층',
     NULL, DEFAULT, DEFAULT);
     
COMMIT;

--로그인 회원 
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICK, MEMBER_TEL,
    MEMBER_ADDR, PROFILE_IMG,
    TO_CHAR(ENROLL_DT,'YYYY-MM-DD HH24:MI:SS') AS ENROLL_DT
    FROM MEMBER 
WHERE MEMBER_EMAIL= 'user01@kh.or.kr' 
AND MEMBER_PW = 'pass01!'
AND SECESSION_FL='N';

--회원가입 확인 
INSERT INTO MEMBER
VALUES (SEQ_MEMBER_NO.NEXTVAL,?,?,?,?,?,NULL,SYSDATE,N);


-- 댓글 테이블 생성
CREATE TABLE REPLY(
  REPLY_NO NUMBER PRIMARY KEY,
  REPLY_CONTENT VARCHAR2(1000) NOT NULL,
  REPLY_ST CHAR(1) DEFAULT 'N' CHECK (REPLY_ST IN ('Y', 'N')),
  CREATE_DT DATE DEFAULT SYSDATE,
  MEMBER_NO NUMBER REFERENCES MEMBER NOT NULL,
  BOARD_NO NUMBER REFERENCES BOARD NOT NULL
);

COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글 번호(PK)';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글  내용';
COMMENT ON COLUMN REPLY.REPLY_ST IS '댓글 상태(Y:정상, N:삭제)';
COMMENT ON COLUMN REPLY.CREATE_DT IS '댓글 작성일';
COMMENT ON COLUMN REPLY.MEMBER_NO IS '댓글 작성 회원 번호';
COMMENT ON COLUMN REPLY.BOARD_NO IS '댓글이 작성된 게시글 번호';

-- 댓글 번호 시퀀스
CREATE SEQUENCE SEQ_RNO NOCACHE;

-- 가장 최근 게시글에 댓글 샘플 데이터 삽입
INSERT INTO REPLY VALUES(SEQ_RNO.NEXTVAL, '댓글 테스트1', DEFAULT, DEFAULT, 1, 500);
INSERT INTO REPLY VALUES(SEQ_RNO.NEXTVAL, '댓글 테스트2', DEFAULT, DEFAULT, 1, 500);

COMMIT;

-- 특정 게시글 댓글 목록 조회 
SELECT REPLY_NO, REPLY_CONTENT,TO_CHAR(CREATE_DT,'YYYY.MM.DD HH24:MI:SS') CREATE_DT,
    BOARD_NO, MEMBER_NO, MEMBER_NICK, PROFILE_IMG
FROM REPLY
JOIN MEMBER USING(MEMBER_NO)
WHERE REPLY_ST ='N'
AND BOARD_NO = 500
ORDER BY REPLY_NO;


--댓글 작성 
INSERT INTO REPLY VALUES(SEQ_RNO.NEXTVAL, ?, DEFAULT, DEFAULT, ?, ?);

--댓글 삭제 
DELETE FROM REPLY
WHERE REPLY_NO =13;


--댓글 수정
UPDATE REPLY SET
REPLY_CONTENT=?
WHERE REPLY_NO = ?;


--다음게시글 번호 조회
SELECT SEQ_BOARD_NO.NEXTVAL FROM DUAL;

--게시글 삽입
INSERT INTO BOARD
VALUES(?,?,?,DEFAULT,DEFAULT,DEFAULT,DEFAULT,?,?);

--게시글 이미지 삽입
INSERT INTO BOARD_IMG
VALUES(SEQ_IMG_NO.NEXTVAL,?,?,?,?);


--게시글 수정
UPDATE BOARD SET
BOARD_TITLE=?,
BOARD_CONTENT=?,
UPDATE_DT=SYSDATE
WHERE BOARD_NO=?;

--게시글 이미지 수정
--?번글 ?레벨의 변경명, 원본명을 수정
UPDATE BOARD_IMG SET
IMG_RENAME=?,
IMG_ORIGINAL=?
WHERE IMG_LEVEL=?
AND BOARD_NO=?;

--게시글 이미지 삭제

--deleteList == "1,2,3"
--pstmt.setString(2,deleteList)

--게시글 삭제 
UPDATE BOARD SET
BOARD_ST='Y'
WHERE BOARD_NO=?;


--2번 게시판의 제목에 "50"포함된 게시글 수
SELECT COUNT(*) FROM BOARD
JOIN MEMBER USING (MEMBER_NO)
WHERE BOARD_ST ='N'
AND BOARD_CD =2
--AND BOARD_TITLE LIKE '%50%'; --제목
--AND BOARD_CONTENT LIKE '%50%' --내용
--AND (BOARD_TITLE LIKE '%50%'OR BOARD_CONTENT LIKE '%50%');  --제목+내용
AND MEMBER_NICK LIKE '%유저일%'; --작성자 


		SELECT * FROM(
			SELECT ROWNUM RNUM, A.* FROM(
				SELECT BOARD_NO , BOARD_TITLE, MEMBER_NICK,
						TO_CHAR(CREATE_DT,'YYYY-MM-DD') AS
						CREATE_DT,
						READ_COUNT
				FROM BOARD
				JOIN MEMBER USING(MEMBER_NO)
				WHERE BOARD_CD = ?
				AND BOARD_ST = 'N'
                
                --condition
                AND BOARD_TITLE LIKE '%50%
                
				ORDER BY BOARD_NO DESC
			) A
		)
		WHERE RNUM BETWEEN ? AND ?

