ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER community_ljy IDENTIFIED BY community1234;

ALTER USER community_ljy DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

GRANT CONNECT, RESOURCE, CREATE VIEW TO community_ljy;


--암호화된 비밀번호 업데이트 
UPDATE MEMBER 
SET MEMBER_PW ='aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg=='
WHERE MEMBER_PW='pass01!';

--MEMBER 테이블 비밀번호 컬럼의 크기 변경
ALTER TABLE MEMBER
MODIFY MEMBER_PW VARCHAR2(100);

--암호화된 비밀번호로 업데이트
UPDATE MEMBER 
SET MEMBER_PW ='aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg=='
WHERE MEMBER_NO=1;

commit;

--회원정보 수정
UPDATE MEMBER
SET MEMBER_NICK=?,
MEMBER_TEL=?,
MEMBER_ADDR=?
WHERE MEMBER_NO=?;

--비밀범호 수정 
UPDATE MEMBER
SET MEMBER_PW = ?
WHERE MEMBER_NO =?
AND MEMBER_PW = ?;


--회원탈퇴
UPDATE MEMBER SET
SECESSION_FL='Y'
WHERE MEMBER_NO=?
AND MEMBER_PW=?;


--이메일 중복 검사 
-- 중복되면 1, 아니면 0 결과 
SELECT COUNT(*) FROM MEMBER
WHERE MEMBER_EMAIL='user01@kh.or.kr'
AND SECESSION_FL='N';


--닉네임 중복검사 
--중복되면 1, 아니면 0 반환
SELECT COUNT(*) FROM MEMBER
WHERE MEMBER_NICK ='유저일'
AND SECESSION_FL = 'N';


--이메일이 일치하는 회원 정보 조회
SELECT MEMBER_EMAIL, MEMBER_NICK, MEMBER_TEL, MEMBER_ADDR,  TO_CHAR(ENROLL_DT, 'YYYY"년" MM"월" DD"일"') AS ENROLL_DT 
FROM MEMBER
WHERE MEMBER_EMAIL= 'user01@kh.or.kr'
AND SECESSION_FL= 'N';


--회원 목록 조회 (회원번호 , 이메일, 닉네임)
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NICK
FROM MEMBER
WHERE SECESSION_FL='N'
ORDER BY MEMBER_NO;


-------------------------------------------------------------------------------------------
-- ""가 없으면, 테이블명, 컬럼명 , 시퀀스명 등을 무조건 대문자로 저장
-- ""가 있으면 대소문자 구분

-- 게시판 종류 
DROP TABLE "BOARD_TYPE";

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CD"	NUMBER		PRIMARY KEY,
	"BOARD_NM"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CD" IS '게시판 코드';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NM" IS '게시판 이름';

--게시판(게시글 저장 테이블) 
DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE" 	VARCHAR2(150)		NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"UPDATE_DT"	DATE		NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_ST"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_CD"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시판번호(시퀀스)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "BOARD"."UPDATE_DT" IS '마지막 수정일';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_ST" IS '게시글 상태(정상Y,  삭제N)';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '작성자 회원번호';

COMMENT ON COLUMN "BOARD"."BOARD_CD" IS '게시판 코드';

--BOARD 테이블 제약조건 추가 
ALTER TABLE BOARD 
ADD PRIMARY KEY(BOARD_NO); --제약조건명을 생략(SYS_XXXXXX)

ALTER TABLE BOARD
ADD CONSTRAINT "FK_BOARD_CD"--제약조건명 지정
FOREIGN KEY ("BOARD_CD") --BOARD의 BORRD _CODE 컬럼에 FK지정
REFERENCES "BOARD_TYPE"; --참조할 테이블명

ALTER TABLE BOARD
ADD CONSTRAINT "CHK_BOARD_ST"
CHECK("BOARD_ST" IN('N','Y'));

ALTER TABLE BOARD
ADD CONSTRAINT "FK_BOARD_MEMBER"
FOREIGN KEY ("MEMBER_NO")
REFERENCES MEMBER;

--BOARD 시퀀스
CREATE SEQUENCE SEQ_BOARD_NO;


--BOARD TYPE 데이터 삽입
INSERT INTO BOARD_TYPE VALUES(1, '공지사항');
INSERT INTO BOARD_TYPE VALUES(2, '자유게시판');
INSERT INTO BOARD_TYPE VALUES(3, '질문게시판');

SELECT * FROM BOARD_TYPE;

--BOARD 테이블 샘플 삽입(PL/SQL)
BEGIN
    FOR I IN 1..500 LOOP
    
        INSERT INTO BOARD
        VALUES(SEQ_BOARD_NO.NEXTVAL,
               SEQ_BOARD_NO.CURRVAL || '번째 게시글',
               SEQ_BOARD_NO.CURRVAL || '번째 게시글 내용입니다.',
               DEFAULT, DEFAULT, DEFAULT, DEFAULT, 1, 3
        );
    END LOOP;
END;
/
--공지사항 게시판 조회
SELECT COUNT(*) FROM BOARD WHERE BOARD_CD =1;
--자유게시판 조회
SELECT COUNT(*) FROM BOARD WHERE BOARD_CD =2;
--질문 게시판 조회
SELECT COUNT(*) FROM BOARD WHERE BOARD_CD =3;




