--로그인 
SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, MEMBER_GENDER, ENROLL_DATE
FROM MEMBER
WHERE MEMBER_ID = 'user01'
AND MEMBER_PW = 'pass01'
AND SECESSION_FL ='N';

--//DB에서 회원 정보 모두 조회 (아이디, 이름, 가입일)
--//단, 탈퇴회원 제외, 아이디 오름차순
SELECT MEMBER_ID, MEMBER_NM, ENROLL_DATE
FROM MEMBER
WHERE SECESSION_FL ='N' --탈퇴안한 사람 제외
ORDER BY MEMBER_ID;

UPDATE MEMBER 
SET MEMBER_NM = '이름', MEMBER_GENDER= 'M'
WHERE MEMBER_NO = 1;

SELECT * FROM MEMBER;
ROLLBACK;